server {
    listen 80;
    server_name localhost;

    # Regras de Firewall (Substitua pelos IPs reais que podem acessar)
    allow 10.7.63.0/24;  # Exemplo: Seu IP de casa
    allow 10.7.60.0/24; # Exemplo: IP do seu trabalho

    deny all;            # Bloqueia qualquer outro IP

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
    }

    # Tratamento elegante para quem for bloqueado
    error_page 403 /403.html;
    location = /403.html {
        root /usr/share/nginx/html;
        internal;
    }
}
