server {
    listen 80;
    server_name localhost;

    # Se quiser liberar para TODO MUNDO ver se funciona:
    allow all;

    # CASO QUEIRA BLOQUEAR: Para liberar a rede interna do Docker + um IP específico:
    # allow 172.16.0.0/12; # Libera a rede interna do Docker (Evita que o Easypanel seja bloqueado)
    # allow SEU_IP_PUBLICO; # Seu IP de internet
    # deny all;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
    }

    error_page 403 /403.html;
    location = /403.html {
        root /usr/share/nginx/html;
        internal;
    }
}
